# Site
name: PyScoop
description: 
baseurl: ""
url:


# Jekyll
permalink: /:title/
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  syntax_highlighter: rouge


sass:
  sass_dir: _sass
  style: compressed


paginate: 5
paginate_path: 'page:num/'


# Gems
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag


# Social
social:
  pyscoop:
    email:
    facebook: https://www.facebook.com/pyscoop
    twitter:
    instagram:
    linkedin:
    github:
  author:
    email:
    facebook: https://www.facebook.com/gjain0
    twitter:
    instagram:
    linkedin: https://www.linkedin.com/in/gjain0
    github:

# External
google_analytics:

firebase:
  apiKey: 
  authDomain: pyscoop-blog.firebaseapp.com
  databaseURL: https://pyscoop-blog.firebaseio.com
  projectId: pyscoop-blog
  storageBucket: pyscoop-blog.appspot.com
  messagingSenderId: 781699840052
