# Site
title: Gaurav Jain
description: Another Python Blog
baseurl: ""
url:

canonical_base_url: https://www.gauravvjn.com


# Jekyll
permalink: /:title/
markdown: kramdown
highlighter: rouge


sass:
  sass_dir: _sass
  style: compressed

static_dir: assets
static_url: /assets

paginate: 5
paginate_path: 'pages:num/'


# Gems/pelican-plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag


# Social
social:
  gauravvjn:
    email:
    facebook: https://www.facebook.com/gauravvjntech
    twitter:
    instagram:
    linkedin: https://www.linkedin.com/in/gauravvjn
    github:
  author:
    email: gauravjain91011@gmail.com
    linkedin: https://www.linkedin.com/in/gauravvjn
    github: http://github.com/gauravvjn
    facebook: https://www.facebook.com/gauravvjn
    twitter: https://twitter.com/gauravvjn
    instagram: 
    sof:

# DSA
dsa_enable: true

dsa_taxonomy:
  # Linked List:
  #   - Singly Linked List
  #   - Circular Linked List
  #   - Doubly Linked List
  #   - Doubly Circular Linked List
  Sorting:
    - Bubble Sort
    - Insertion Sort
    - Selection sort
    - Merge Sort
    - Quick Sort
    - Heap Sort
  Searching:
    - Linear Search
    - Binary Search
  Stack:
  # Queue:
  #   - Queue
  #   - Double Ended queue (Deque)
  #   - Priority Queue
  # Tree & Heap:
  #   - Binary Tree
  #   - Binary Search Tree (BST)
  #   - AVL Tree
  #   - Heap
  # Graph:


# External
google_analytics: UA-110940448-1

