# Site
title: PyScoop
description: Another Python Blog
baseurl: ""
url:

canonical_base_url: https://www.pyscoop.com


# Jekyll
permalink: /:title/
markdown: kramdown
highlighter: rouge


sass:
  sass_dir: _sass
  style: compressed

static_dir: assets
static_url: /assets

paginate: 5
paginate_path: 'page:num/'


# Gems/plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag


# Social
social:
  pyscoop:
    email:
    facebook: https://www.facebook.com/pyscoop
    twitter:
    instagram:
    linkedin:
    github:
  author:
    email:
    facebook: https://www.facebook.com/gjain0
    twitter:
    instagram:
    linkedin: https://www.linkedin.com/in/gjain0
    github: http://github.com/gjain0
    sof:

# DSA
dsa_enable: true

dsa_taxonomy:
  # Linked List:
  #   - Singly Linked List
  #   - Circular Linked List
  #   - Doubly Linked List
  #   - Doubly Circular Linked List
  Sorting:
    - Bubble Sort
    - Insertion Sort
    - Selection sort
    - Merge Sort
    - Quick Sort
    - Heap Sort
  Searching:
    - Linear Search
    - Binary Search
  Stack:
  # Queue:
  #   - Queue
  #   - Double Ended queue (Deque)
  #   - Priority Queue
  # Tree & Heap:
  #   - Binary Tree
  #   - Binary Search Tree (BST)
  #   - AVL Tree
  #   - Heap
  # Graph:


# External
google_analytics: UA-110940448-1

firebase:
  apiKey: 
  authDomain: pyscoop-blog.firebaseapp.com
  databaseURL: https://pyscoop-blog.firebaseio.com
  projectId: pyscoop-blog
  storageBucket: pyscoop-blog.appspot.com
  messagingSenderId: 781699840052
